-- Wind Turbine POC pipeline setup: database, schemas, warehouse, stage, and ETL role for the pipeline

----------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS WIND_TURBINE_POC;
CREATE SCHEMA IF NOT EXISTS WIND_TURBINE_POC.STAGING;
CREATE SCHEMA IF NOT EXISTS WIND_TURBINE_POC.CLEANED;
CREATE SCHEMA IF NOT EXISTS WIND_TURBINE_POC.MART;

CREATE WAREHOUSE IF NOT EXISTS WIND_TURBINE_POC_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

----------------------------------------------------------------------

CREATE ROLE IF NOT EXISTS POC_ETL_ROLE;

GRANT USAGE ON DATABASE WIND_TURBINE_POC TO ROLE POC_ETL_ROLE;
GRANT USAGE ON SCHEMA WIND_TURBINE_POC.STAGING TO ROLE POC_ETL_ROLE;
GRANT USAGE ON SCHEMA WIND_TURBINE_POC.CLEANED TO ROLE POC_ETL_ROLE;
GRANT USAGE ON SCHEMA WIND_TURBINE_POC.MART TO ROLE POC_ETL_ROLE;
GRANT ALL ON SCHEMA WIND_TURBINE_POC.STAGING TO ROLE POC_ETL_ROLE;
GRANT ALL ON SCHEMA WIND_TURBINE_POC.CLEANED TO ROLE POC_ETL_ROLE;
GRANT ALL ON SCHEMA WIND_TURBINE_POC.MART TO ROLE POC_ETL_ROLE;

GRANT USAGE, OPERATE ON WAREHOUSE WIND_TURBINE_POC_WH TO ROLE POC_ETL_ROLE;

-- Stage
----------------------------------------------------------------------

CREATE STAGE IF NOT EXISTS WIND_TURBINE_POC.STAGING.WIND_TURBINE
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

GRANT READ, WRITE ON STAGE WIND_TURBINE_POC.STAGING.WIND_TURBINE TO ROLE POC_ETL_ROLE;

