USE ROLE POC_ETL_ROLE;
USE DATABASE WIND_TURBINE_POC;

-- Tables
-----------------------------------------------------------------------
-- files table
CREATE TABLE IF NOT EXISTS  WIND_TURBINE_POC.STAGING.FILE_LOAD_HISTORY 
(   FILE_NAME            VARCHAR NOT NULL,
    FILE_LAST_MODIFIED   TIMESTAMP_TZ NOT NULL,
    FILE_CHECKSUM        VARCHAR NOT NULL,
    FILE_SIZE            INTEGER NOT NULL,
    STATUS               VARCHAR NOT NULL,
    STATUS_DATETIME      TIMESTAMP_NTZ NOT NULL
);

-- Staging table
CREATE TABLE IF NOT EXISTS WIND_TURBINE_POC.STAGING.STG_TURBINE_MEASUREMENT 
(   MEASUREMENT_TIMESTAMP   VARCHAR,
    TURBINE_ID      VARCHAR,
    WIND_SPEED      VARCHAR,
    WIND_DIRECTION  VARCHAR,
    POWER_OUTPUT    VARCHAR,
    SOURCE_FILE     VARCHAR NOT NULL,
    LOADED_DATETIME TIMESTAMP_NTZ NOT NULL
);

-----------------------------------------------------------------------
-- Cleaned tables
-- Turbine dimension
CREATE TABLE IF NOT EXISTS WIND_TURBINE_POC.CLEANED.TURBINE
(   TURBINE_ID      INTEGER NOT NULL,
    SOURCE_FILE     VARCHAR NOT NULL,
    CREATED_DATETIME DATETIME NOT NULL
);

-- Turbine fact
CREATE TABLE IF NOT EXISTS WIND_TURBINE_POC.CLEANED.TURBINE_MEASUREMENT 
(   MEASUREMENT_TIMESTAMP   VARCHAR NOT NULL,
    MEASUREMENT_DATE    DATE NOT NULL,
    TURBINE_ID      INTEGER NOT NULL,
    WIND_SPEED      NUMBER(10,3) NOT NULL,
    WIND_DIRECTION  INTEGER NOT NULL,
    POWER_OUTPUT    NUMBER(10,3) NOT NULL,
    DAILY_AVG_POWER_OUTPUT    NUMBER(10,3) NOT NULL,
    DAILY_STDDEV_POWER_OUTPUT    NUMBER(10,3) NOT NULL,
    IS_ANOMALY BOOLEAN  NOT NULL,
    SOURCE_FILE     VARCHAR NOT NULL,
    LOADED_DATETIME DATETIME NOT NULL,
    CLEANED_DATETIME DATETIME NOT NULL
);

-----------------------------------------------------------------------
-- Mart tables
-- Daily Turbine statistics
CREATE TABLE IF NOT EXISTS WIND_TURBINE_POC.MART.DAILY_TURBINE_STATS
(   MEASUREMENT_DATE    DATE NOT NULL,
    TURBINE_ID      INTEGER NOT NULL,
    MEASUREMENT_COUNT INTEGER NOT NULL,
    MIN_POWER_OUTPUT    NUMBER(10,3) NOT NULL,
    MAX_POWER_OUTPUT    NUMBER(10,3) NOT NULL,
    AVG_POWER_OUTPUT    NUMBER(10,3) NOT NULL,
    AGGREGATION_DATETIME DATETIME NOT NULL
);

